tokamak-network/dao-agenda-metadata-repository

data/agendas/sepolia/agenda-64.json

- Agenda ID: 64
- Title:Test Agenda 
- Transaction Hash: 0xf011feaead3f5b09beaa45d1de573f38aebdcbe0a0920ed8c8a42a2e806b2d5c
- Signature: 0xbed3d0da012a44827cdc530ec68198ff4d4034e68afc44d89b9517e85cf34d7e6adf261df4a07a512fee9c659ce5d5f72465a3f777bca97759fc8fec1c830a5c1b
Test Agenda Description

[Agenda] sepolia - 64 - Test Agenda

---

data/agendas/sepolia/agenda-69.json

- Agenda ID: 69
- Title: This Agenda is Test
- Transaction Hash: 0xed94abf02fde17cecc61ab3c2830eafe38508a3430b720f1ce584f5052c473e4
- Signature: 0xff4fd8785957cdbaac2760b1c8c54f5fec1535df0195f4bbc9b1350e7c72425062d3bfdd7bb67c5407287f9a343282ce54a1ad6f112c62da13ae8817d28d95b51b
Test agenda

[Agenda] sepolia - 69 - This Agenda is Test

---

data/agendas/sepolia/agenda-70.json

- Agenda ID: 70
- Title: Title
- Transaction Hash: 0x16ba582c4b68ead6d819e3bf62da90d3bccccb134e8b31b2965838204146b82b
- Signature: 0xb040bbf895a1e70880a2448c8b2d0effaa444cb99f0c2694982cb214d98a256b4f23b628e3195eabfb5a175a7f9f298669fa841362d37040720bf4b885cd7d8b1c
**Description** a

[Agenda] sepolia - 70 - Title

---

data/agendas/sepolia/agenda-76.json

- Agenda ID: 76
- Title: Title
- Transaction Hash: 0x6e7e090b01316fac833ec568ea7cc202ea131db596c097fe3b0b7566228f78c9
- Signature: 0x22653123c7bdfae1855338c739dddc708b5e353f2f6b958e50fb18b459965b092fcecd4dfe4a55b9056cc24ceb71cb8247903d146b2fc2b0267cc66b5c6a19db1c
Description

[Agenda] sepolia - 76 - Title

---

data/agendas/sepolia/agenda-77.json

- Agenda ID: 77
- Title: Test 2
- Transaction Hash: 0xf3760eb0452fa6c87ccf3ab943659a70b313b027da842156b9a6e2ee9b428d9a
- Signature: 0x06bff55dec1c3e636c4d80579f1cc9287c3e8672da3d5f2ab5cb5b61e12c60396e67ecf19d1d2c0aead898f03d36e8a56dcf47d1385f414f7dd27be178f7dcb71b
Description

[Agenda] sepolia - 77 - Test 2

---

data/agendas/sepolia/agenda-78.json

- Agenda ID: 78
- Title: Running test
- Transaction Hash: 0x5d69bb4d743993120cbca55446c048bbebe3486963d57b1f70a34dc5eee84b1f
- Signature: 0x0053cdfdc856044ae562c9e50de07bae94fe767a30ebac7fa395ce156b597d7f39c84cd230c23532c6c4816024eaa8a0343516637443f4705c38737cd7f64fd61c
**Description**

[Agenda] sepolia - 78 - Running test

---

data/agendas/sepolia/agenda-80.json

- Agenda ID: 80
- Title: updateSeigniorageLayer
- Transaction Hash: 0x597cd2b5f29caeec39ed995c98b0cfe683d6508ae2f518be9ec1258a03471ac6
- Signature: 0x98740a893bc2b6956adc1348d5e421771f445a6810248578482ba1b28b1ba0740ef643933359a01ee5ead58ecbe326d9bbf20a0f939330fc286545b125b890bb1b
updateSeigniorageLayer

[Agenda] sepolia - 80 - updateSeigniorageLayer

---

data/agendas/sepolia/agenda-88.json

- Agenda ID: 88
- Title: Another Test 5
- Transaction Hash: 0xc819e7715773a13abd261b5865d52b402990a11fb97761e4c41b833286d81d91
- Signature: 0xc67926e63d5a3bbe5c555143140d88311f9b79ee8d78fefeb55f99044e84194a4dc42fab09ec5a6fc018a0ed0be9b7a8ec099e583c64d6802c375429cba702e21c

[Agenda] sepolia - 88 - Another Test 5

---

data/agendas/sepolia/agenda-84.json

- Agenda ID: 84
- Title: Another Test 2
- Transaction Hash: 0xd140219e841905317a0d48bd8d326f76068d9d7f971fbad52562e462b61f27f4
- Signature: 0x2c8d7a703cbd62ad8103351644eb145de78931f2f8bb7a7537b24988b8e147f30b205cfa83eede3610d1e068bcaf1ab7442cdb4690c5e9d30b2a4b9c67c3e8ba1c

[Agenda] sepolia - 84 - Another Test 2

---

data/agendas/sepolia/agenda-90.json

- Agenda ID: 90
- Title: Another Test 7
- Transaction Hash: 0x3476190423238ba531df752df913ea2171c7e2612795a38343651a1f270916b5
- Signature: 0xc5307c00ffc622e6c9833796106205426fda5e9e0a07d5fe325b65498e61007714a341ab417cffc452f13002f8610f03875f08881836532298f79eeeb40386841b

[Agenda] sepolia - 90 - Another Test 7

---

data/agendas/sepolia/agenda-91.json

- Agenda ID: 91
- Title: Another Test 8
- Transaction Hash: 0x25f98656e7971380209896be896535946911d26aabba6a6b784259a91bc9ab80
- Signature: 0xc10b3e308b103f17b06df8b1bbfa532901af45db855418ecf5036e4e08e6e1484f24cd94d41d7abb921f4b5f1c2f35c849798817469a7bee3adfc2e3fe1f811a1b
Another Test

[Agenda] sepolia - 91 - Another Test 8

---

data/agendas/sepolia/agenda-92.json

- Agenda ID: 92
- Title: Test
- Transaction Hash: 0x508a9e391f348470d957c4a76885cba6a5f583b7a30ccc5f1cd59fd0e6b4658e
- Signature: 0x1ae615f058631dbbb13e9314fd7a4afff707365abc77ace30ba897d1e8d989e72690f6136ba660c0f1c94e129670a24369e40a730e1a515100e71f2535f6f4281b

[Agenda] sepolia - 92 - Test

---

data/agendas/sepolia/agenda-94.json

- Agenda ID: 94
- Title: Test
- Transaction Hash: 0x2d550d5d8166a0c6f326c9daca3158950bb64f3c2a0806b06173580a3989689a
- Signature: 0x00a45933425ff6db8121b110afdd16def113a70bcce43a8f9594be33d845d538529ea5370afd896994066c4480b62f8fcf04c8629cbcda15be9b1220f671c4bf1b

[Agenda] sepolia - 94 - Test

---

data/agendas/sepolia/agenda-95.json

- Agenda ID: 95
- Title: Today..agenda
- Transaction Hash: 0x3ea10c1664a2a102578db8e04dd973481a0378c22b27a60d00691086de1381ee
- Signature: 0x766eaabba758cb58d84d8d02df389ab9cc5832b71cdf2e890bcf1a639d0076196790bb637436c0130454a8f7b97a10a4879d73787129b94c34449a6d991b11401b

[Agenda] sepolia - 95 - Today..agenda

---

data/agendas/sepolia/agenda-99.json

- Agenda ID: 99
- Title: Version Test - 2
- Transaction Hash: 0x215b27f726c7afbbbe3c19274547e011cfeddbee3e663aa035b9bf0501c25456
- Signature: 0xd479d035ca55f0a95c55b5214aab2338162ac2df2fedc20f392542d2b8d0cab21cfb68d41b9686c9fd3120b384a76ed2e7987b0c5891eb88a23563553acff9a61c

[Agenda] sepolia - 99 - Version Test - 2

---

data/agendas/sepolia/agenda-116.json

- Agenda ID: 116
- Title: Test5 - 20250617
- Transaction Hash: 0xddcdbfbeffb6f00769f25da9514abbe60b94d466e88d9f5a4751d65e513d6ea4
- Signature: 0xe6f6e3285624b6ce8d6267de5195a54ba71a9dffa7d5d0896fe224ac1d50df974582f237445de6eb862087092a47a43a88837c41ef60035765e893d20f0d99c21c

[Agenda] sepolia - 116 - Test5 - 20250617

---

data/agendas/sepolia/agenda-117.json

- Agenda ID: 117
- Title: Proposal Test
- Transaction Hash: 0xe9d778cbcbad7803edfd4ccc0422a0eede805a0402c1867d8577b3d0be1d1090
- Signature: 0xcdca18949e1e3db32af072b036aab66697daff5e70a2bfd71d826656b255331a5b24e90aba70b06231e7c0baad26055a8c536d147194ae6d0bb8f285cd0a94a71c

[Agenda] sepolia - 117 - Proposal Test

---

data/agendas/sepolia/agenda-134.json

- Agenda ID: 134
- Title: MergeTest-11
- Transaction Hash: 0x92092942478ed3f9bd0142836f23c7c796dbd459f89804ca5f2b782445e85975
- Signature: 0x8bf1059cde140d4c48c8d79f80f9f05493bccc13f875203a59d87fa7da15151019cde205d9ef17d046ca183a673b6061cbcb808aa5c40c4db533b5e198955edc1b
Agenda submission for sepolia network - MergeTest-11

[Agenda] sepolia - 134 - MergeTest-11

---

data/agendas/sepolia/agenda-135.json

- Agenda ID: 135
- Title: MergeTest-12
- Transaction Hash: 0x5589d45f3f0fb531ab209a69022f3f3270403242e1b8975d5e3b66029b606a9a
- Signature: 0xad0372fae6d4a2ed5c88304bd29edd2ceee7457e67a53e152fe10b876e52afbe646ff460d416bf4c338d65af4bc87806456dcfeaa8abdd4e4cb5f5281659cb911b
Agenda submission for sepolia network - MergeTest-12

[Agenda] sepolia - 135 - MergeTest-12

---

data/agendas/sepolia/agenda-137.json

- Agenda ID: 137
- Title: MergeTest-14
- Transaction Hash: 0xdc5fe14710ec3f78942feb84d92e9cdf14ff1db1bfbe0ccadaaf9251d921229f
- Signature: 0xa654d7e0a94fda8f3a65c373124c976f6161c05bb46fd69faa803274b3eae3a17456c5c346a4d86c919b4802b92ed4c445892f73297a6ff5cadb1be523411df51c
Agenda submission for sepolia network - MergeTest-14

[Agenda] sepolia - 137 - MergeTest-14

---

data/agendas/sepolia/agenda-138.json

- Agenda ID: 138
- Title: test 0703
- Transaction Hash: 0x87d4ce80b2d9d931ca51619bab2afba4b9c6b13374571f6b106fba7fd41844f3
- Signature: 0xa0120fe18ca1afca6cffb97a65f5a47f7ea4a0c7efff19440619be1efc8fe0ae671dbc94406ad5972419b2cb085e2bb3d0b9932a401af5fd21c995ed6838a8b01c
Agenda submission for sepolia network - test 0703

[Agenda] sepolia - 138 - test 0703

---

data/agendas/sepolia/agenda-139.json

- Agenda ID: 139
- Title: test-page-1
- Transaction Hash: 0xdbf75321b1abe529f39dadc8260bf710ef946c0dec793a57e0cbee8c26fba946
- Signature: 0x5913cb19a50de8eeb3b2a353aa6ad9245021cc316e0dc3e7eaee83edf090f18612f5d8fa341d459619c6040d16be4096974e66e7f3036f53c3ce1e3eb011b45a1b
Agenda submission for sepolia network - test-page-1

[Agenda] sepolia - 139 - test-page-1

---

data/agendas/sepolia/agenda-145.json

- Agenda ID: 145
- Title: Update Seigniorage
- Transaction Hash: 0x2f32794113bf5d24eddb3cdb6f81d4548248d94f4b4fa22515c3b2a5649911cb
- Signature: 0xebca7c0f340195cbc4b2a60e1d56989878346ab3a9b8d2d3c180e6a4e7a848883d6c8246f253814ef04402693d5cad17513a138b766c87b5dde8f1afb5e2f9931c
Agenda submission for sepolia network - Update Seigniorage

[Agenda] sepolia - 145 - Update Seigniorage

---

data/agendas/sepolia/agenda-146.json

- Agenda ID: 146
- Title: Demo 0715
- Transaction Hash: 0x18029f06cadef3af078e106e1f7a15403663664feeb68c0c2c9692009472b88d
- Signature: 0x7e6e95480db0a0a7032858971b52575142f775e1640758fde26273c345b262e1340d316672446c27e0c305429f25c66f07ec8fc61b9e0bd84e86c4bed80e98651c
Agenda submission for sepolia network - Demo 0715

[Agenda] sepolia - 146 - Demo 0715

---

data/agendas/sepolia/agenda-148.json

- Agenda ID: 148
- Title: setMinimumNoticePeriodSeconds to 150
- Transaction Hash: 0xa193bc1b01761413ba187030b8eff2126a12cde3c544ec55a20c0873aa075a48
- Signature: 0x70645dc46f61afeb1c87e3fcd7352ed3355ed98cf194dac22e54294c8cc7a9dd08fa35c160b8c5e4dde9eff3d4bea1220091d541fe46ec94f992c450ba7e79c51b
Agenda submission for sepolia network - setMinimumNoticePeriodSeconds to 150

[Agenda] sepolia - 148 - setMinimumNoticePeriodSeconds to 150

---

data/agendas/sepolia/agenda-140.json

- Agenda ID: 140
- Title: Test-3
- Transaction Hash: 0xa2a0d1a88f1b436e2a6e0eee258144b8d0db6117d888643150d0f686fbac8321
- Signature: 0xf3658a6ea414b258a932d6cc831b226b39918c653e22603bbe7d4edc6e325bdd1fd62c67d8131ee428838f71f6137571b2a2d2d5a3ead0f254cb3b170abd381d1c
Agenda submission for sepolia network - Test-3

[Agenda] sepolia - 140 - Test-3

---

data/agendas/sepolia/agenda-147.json

- Agenda ID: 147
- Title: Demo 0715-2
- Transaction Hash: 0x84962f104e94aee96e2a69d7eea98e590c4aca777b9ec9d664cdc58d2978e1db
- Signature: 0xc8d6320e9527c3ef313d41a94c3fec81ac2356b4b4fbcd0c47cfb560b26be2f77bbf5cdb8e40432b12377df495867902cca4467b16330172bf169207d25781d61c
Agenda submission for sepolia network - Demo 0715-2

[Agenda] sepolia - 147 - Demo 0715-2

---

data/agendas/sepolia/agenda-154.json

- Agenda ID: 154
- Title: DAO Test is good?
- Transaction Hash: 0x3bad4f078792d76f1e2d514c4d1bd5e8873371e2ab2ff43aacaa933e514c0cc8
- Creator Address: 0x7628340F8Fca5EB6fdC1497aeCA25Bfaa1E080dd
- Signature: 0x7b16340a3b85620110e815e3224609d7e49827075e0562d3cb90b2e4476e19ff1a64c7858428b44fec4cc97ecc7ff0d96792ae974b751a08b6dab306b30215561c
Agenda submission for sepolia network - DAO Test is good?

[Agenda] sepolia - 154 - DAO Test is good?

---

data/agendas/sepolia/agenda-155.json

- Agenda ID: 155
- Title: DAO Test
- Transaction Hash: 0x9d0988d0ea49331ab7cb37b79587986a00a6b069f60d82c86251bd5bb52b8799
- Creator Address: 0xD7D57ba9F40629d48c4009a87654CDDa8A5433E9
- Signature: 0xadef7b26fb32da050a303b8b404a823fbebd6c22d13e5fcd791b0bcba870259052dea1b05647146f7b009364ee4e9a485080d6320b895348fa10731147528cba1c
Agenda submission for sepolia network - DAO Test

[Agenda] sepolia - 155 - DAO Test

---

data/agendas/sepolia/agenda-173.json

- Agenda ID: 173
- Title: test
- Transaction Hash: 0x5a99ae27efc9e095370fc04447a947e6a2d1aa7325209edc2726f3b240bda66c
- Creator Address: 0x73A7F5D50aD88FcaAe05Da093316BF7d99a27e45
- Signature: 0x5ece7dbe0a3926c406c272d95e8f0c999ce78df0c30dd9d3c5b26e9883dceddb789ca5c3f38db22dbc4f202809f39e37deca8911a7abfde4796fe047e245ab241b
Agenda submission for sepolia network - test

[Agenda] sepolia - 173 - test

---

data/agendas/sepolia/agenda-174.json

- Agenda ID: 174
- Title: Test-pr-button
- Transaction Hash: 0xf03069187b3b1eccb285a19ecb8bf942f2772827f9b9a42bcc2940a1cc6a7697
- Signature: 0xf85cd23279384707869668063e7ed9f7ec208091a1b21110741bea7e4e328e950dd968506b768baacb0d5eda97815bac0be9a9b83664635d175b5decd36adaaf1c
Agenda submission for sepolia network - Test-pr-button

[Agenda] sepolia - 174 - Test-pr-button

---

data/agendas/sepolia/agenda-176.json

- Agenda ID: 176
- Title: test-pr-3
- Transaction Hash: 0x95e35c32357bd448970a4ac89548d8bddb6253ce7976e3a84d222c679f8d6a7b
- Signature: 0x6a70046340fb76e94b8e42ff6eae2dd0406f280e7458e245e6ceee929c3c751a110c9cf9cd9ee05eb66d1860f0ecd7b35a718e4db1b6df386602fee3f4f2997a1c
Agenda submission for sepolia network - test-pr-3

[Agenda] sepolia - 176 - test-pr-3

---

data/agendas/sepolia/agenda-175.json

- Agenda ID: 175
- Title: test-pr-2
- Transaction Hash: 0xf3098655a2fc622aa139d1ce8e45bacdd6a4d649e02bc21ca225c0537dc19a95
- Signature: 0xbb953cd545097b206cff6b20d646d46aa416dd2551a8053ba55b9e3cca838aa3039c44c2628d81452634b3dc92482220997d54dd554266dc92a70d3201d8ba361c
Agenda submission for sepolia network - test-pr-2

[Agenda] sepolia - 175 - test-pr-2

---

data/agendas/sepolia/agenda-177.json

- Agenda ID: 177
- Title: test-pr-4
- Transaction Hash: 0xfe3643737ab54c272e5ff3b03e76f6c525bba19c94777c43bdf973dcf3180119
- Signature: 0xfd855adc8ffcf8c22ed88890df7baa72b09caff8675600651dbeac67cdfd863a16027776585c28b545986fbffbe62ac0d32774f2d609e248be0275ae8481e1371c
Agenda submission for sepolia network - test-pr-4

[Agenda] sepolia - 177 - test-pr-4

---

data/agendas/sepolia/agenda-179.json

- Agenda ID: 179
- Title: test-pr-4
- Transaction Hash: 0x20f72766a8c689e7de344292e49d82a0124e2bc0689a8efe5943182be7f267c2
- Signature: 0x88851d614c51a4dc25fdb166b7a13003d288305754f687d808ddaa4937d660f97bbd17523a3a5869c3087b08954a29474b333af4876327ce24cb8a083357d39c1c
Agenda submission for sepolia network - test-pr-4

[Agenda] sepolia - 179 - test-pr-4

---

data/agendas/mainnet/agenda-11.json

**For new agenda:**
`[Agenda] <network> - <agenda_id> - <agenda_title>`
**For agenda update:**
`[Agenda Update] <network> - <agenda_id> - <agenda_title>`
Examples:
- `[Agenda] mainnet - 1 - Increase Treasury Allocation`
- `[Agenda Update] sepolia - 2 - Updated Treasury Proposal`
---
---
💡 **Need help?** Check the [documentation](docs/) for detailed guides on metadata format, validation, and signature creation.

[Agenda] mainnet - 11 - DepositManagerAddition

---

data/agendas/mainnet/agenda-13.json

**For new agenda:**
`[Agenda] <network> - <agenda_id> - <agenda_title>`
**For agenda update:**
`[Agenda Update] <network> - <agenda_id> - <agenda_title>`
Examples:
- `[Agenda] mainnet - 1 - Increase Treasury Allocation`
- `[Agenda Update] sepolia - 2 - Updated Treasury Proposal`
---
---
💡 **Need help?** Check the [documentation](docs/) for detailed guides on metadata format, validation, and signature creation.

[Agenda] mainnet - 13 - DAOcontractUpgrade

---

data/agendas/mainnet/agenda-15.json

**For new agenda:**
`[Agenda] <network> - <agenda_id> - <agenda_title>`
**For agenda update:**
`[Agenda Update] <network> - <agenda_id> - <agenda_title>`
Examples:
- `[Agenda] mainnet - 1 - Increase Treasury Allocation`
- `[Agenda Update] sepolia - 2 - Updated Treasury Proposal`
---
---
💡 **Need help?** Check the [documentation](docs/) for detailed guides on metadata format, validation, and signature creation.

[Agenda] mainnet - 15 - DAOContractUpgrade

---

data/agendas/mainnet/agenda-12.json

**For new agenda:**
`[Agenda] <network> - <agenda_id> - <agenda_title>`
**For agenda update:**
`[Agenda Update] <network> - <agenda_id> - <agenda_title>`
Examples:
- `[Agenda] mainnet - 1 - Increase Treasury Allocation`
- `[Agenda Update] sepolia - 2 - Updated Treasury Proposal`
---
---
💡 **Need help?** Check the [documentation](docs/) for detailed guides on metadata format, validation, and signature creation.

[Agenda Update] mainnet - 12 - seigniorageRatesChange
